name: "Generate Allure Report"
description: "Load report history and generate Allure Report"
inputs:
  github-token:
    description: "GitHub token for authentication"
    required: true
runs:
  using: "composite"
  steps:
    - name: Load test report history
      uses: actions/checkout@v3
      if: always()
      continue-on-error: true
      with:
        ref: allure-gh-pages
        path: allure-gh-pages

    - name: Build test report
      uses: simple-elf/allure-report-action@v1.7
      if: always()
      with:
        gh_pages: allure-gh-pages
        allure_history: allure-history
        allure_results: e2e-tests/build/allure-results

    - name: Publish test report
      uses: peaceiris/actions-gh-pages@v3
      if: always()
      with:
        github_token: ${{ inputs.github-token }}
        publish_branch: allure-gh-pages
        publish_dir: allure-history