name: On windows
on: [push]
jobs:
  test:
    name: "Run all tests on windows"
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17

      - name: Grant execute permission for Gradlew
        run: git update-index --chmod=+x gradlew
        shell: bash

      - name: Run tests
        run: ./gradlew clean test
        shell: bash

#      - name: Run tests
#        run: ./gradlew.bat clean test
#        shell: powershell

      - name: Upload test reports111
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports1
          path: build/reports/tests/test

      - name: Upload test reports222
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports2
          path: build

      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: e2e-tests/build/allure-results

  allure-report:
    name: "Generate Allure HTML report"
    runs-on: ubuntu-latest
    if: always()
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Download Allure results
        uses: actions/download-artifact@v4
        with:
          name: allure-results
          path: e2e-tests/build/allure-results

      - name: Load test report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: e2e-tests/build/allure-results

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history