#name: Playwright Java Tests
#
#on:
#  workflow_dispatch:   # manual trigger
#  push:                # run on push
#    branches: [ main ]
#  pull_request:
#
#jobs:
#  test:
#    runs-on: ubuntu-latest
#
#    steps:
#      # 1. Checkout repository
#      - uses: actions/checkout@v4
#
#      # 2. Set up JDK
#      - name: Set up JDK 17
#        uses: actions/setup-java@v4
#        with:
#          distribution: temurin
#          java-version: 17
#
#      # 3. Cache Gradle dependencies
#      - name: Cache Gradle packages
#        uses: actions/cache@v3
#        with:
#          path: |
#            ~/.gradle/caches
#            ~/.gradle/wrapper
#          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
#          restore-keys: |
#            ${{ runner.os }}-gradle-
#
#      # 4. Run tests
#      - name: Download arch
#        run: wget https://github.com/JetBrains/data-context-engine/actions/runs/17917651616/artifacts/4072709277d -O file.pdf && xdg-open file.pdf
#      - name: Run tests
#        run: ./gradlew test
